### ISSUE TITLE
File encoding read error

### ISSUE THREAD

**Issue by sambles** [OasisLMF/omdk#11]
```
sompo ~/Catrisks $ file -i tests/meeq_locexp.csv
tests/meeq_locexp.csv: text/plain; charset=iso-8859-1

sompo ~/Catrisks $ file -i tests/MEEQ/SourceExposure/MEEQ_loc.csv
tests/MEEQ/SourceExposure/MEEQ_loc.csv: text/plain; charset=us-ascii
```
```
2018-03-06 16:50:18,568 - INFO - Generating canonical exposures file /home/centos/omdk/runs/ProgOasis-20180306165014/tmp/canexp-20180306165018.csv
Traceback (most recent call last):
  File "generate_oasis_files.py", line 280, in <module>
    oasis_files = manager.start_files_pipeline(model, with_model_resources=False, **args)
  File "/home/centos/omdk/exposures/OasisExposuresManager.py", line 1041, in start_files_pipeline
    canonical_exposures_file = self.transform_source_to_canonical(oasis_model, with_model_resources=False, **kwargs)
  File "/home/centos/omdk/exposures/OasisExposuresManager.py", line 278, in transform_source_to_canonical
    PyTrans(pytrans_args)()
  File "/home/centos/omdk/exposures/PyTrans.py", line 87, in __call__
    for csv_input_slice in self.file_NextSlice(fd_input):
  File "/home/centos/omdk/exposures/PyTrans.py", line 210, in file_NextSlice
    self.row_end
  File "/home/centos/omdk/exposures/PyTrans.py", line 233, in file_ReadSlice
    return [line for line in file_slice]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb4' in position 77: ordinal not in range(128)
```

**Comment by sambles** [comment]
one option is to ignore and hope for the best
```
 79         with io.open(self.fpath_input, 'r', errors = 'ignore') as fd_input:
```

**Comment by sr-murthy** [comment]
I don't think that is a good solution - reading/writing text files in Python should use an appropriate encoding standard, in this case UTF-8. There is absolutely no problem in having Unicode characters in source files - you're getting these errors because when you're reading text files you're not declaring the UTF-8 encoding standard, e.g. the correct way of reading text files in a Unicode friendly way is

    ...
    with io.open('/path/to/input/file', 'r', encoding='utf-8') as f:
        ...
    ...

And when you're writing text files similarly you're not declaring the same attribute, e.g.

    ...
    with io.open('/path/to/output/file', 'w', encoding='utf-8') as f:
        ...
    ...
